run_name: "DDPM_conditional_comp_2"
epochs: 300
batch_size: 64
image_size: 64
num_classes: 10
dataset_path: "data/cifar10-64/train"
device: "cuda"
learning_rate: 6.4e-4
evaluation_interval: 10
fid: "off"
wandb: True
mixed_precision: True
distillation: False
compress: True
