run_name: "DDPM_conditional"
epochs: 1
batch_size: 64
image_size: 64
num_classes: 10
dataset_path: "data/cifar10-64/train"
device: "cuda"
learning_rate: 6.4e-4
evaluation_interval: 10
fid: "on"
wandb: False
mixed_precision: True
distillation: False
compress: True
