run_name: "DDPM_conditional_KD_MPT_ADD_LOSS"
epochs: 300
batch_size: 64
image_size: 64
num_classes: 10
dataset_path: "data/cifar10-64/train"
device: "cuda"
learning_rate: 6.4e-4
evaluation_interval: 50
fid: "on"
wandb: True
mixed_precision: True
distillation: True
compress: True