run_name: "Pruned_0.1_0.01_FT"
epochs: 100
batch_size: 64
image_size: 64
num_classes: 10
dataset_path: "data/cifar10-64/train"
device: "cuda"
learning_rate: 6.4e-4
evaluation_interval: 10
fid: "off"
wandb: True
model_path: "./models/pruned/ddpm_conditional_pruned/pruned/unet_pruned_0.16_0.01.pth"